// Central Configuration for All Widgets
// Generated by Branding Settings
// Modular - Each widget has independent styling

const DEFAULT_CONFIG = {
    fontFamily: "Oswald",
    googleFont: true,
    fontWeight: "bold",
    textShadow: "2px 2px 4px rgba(0,0,0,0.8)",
    
    layout: {
        gap: 2
    },
    
    widgets: {
        followers: {
            fontSize: 48,
            labelFontSize: 14,
            colors: {
                text: "#9146ff",
                label: "#aaaaaa",
                border: "#9146ff",
                background: "rgba(0,0,0,0.3)"
            },
            border: {
                width: 2,
                style: "solid",
                radius: 0
            },
            background: {
                enabled: true,
                color: "#a80b0b",
                opacity: 30
            },
            padding: {
                vertical: 8,
                horizontal: 15
            }
        },
        monthly: {
            fontSize: 42,
            labelFontSize: 14,
            colors: {
                text: "#ff6b6b",
                label: "#aaaaaa",
                border: "#ff6b6b",
                background: "rgba(0,0,0,0.3)"
            },
            border: {
                width: 2,
                style: "solid",
                radius: 0
            },
            background: {
                enabled: false,
                color: "rgba(0,0,0,0.3)",
                opacity: 30
            },
            padding: {
                vertical: 8,
                horizontal: 15
            }
        },
        lifetime: {
            fontSize: 36,
            labelFontSize: 14,
            colors: {
                text: "#ffd700",
                label: "#aaaaaa",
                border: "#ffd700",
                background: "rgba(0,0,0,0.3)"
            },
            border: {
                width: 2,
                style: "solid",
                radius: 0
            },
            background: {
                enabled: false,
                color: "rgba(0,0,0,0.3)",
                opacity: 30
            },
            padding: {
                vertical: 8,
                horizontal: 15
            }
        }
    }
};

let WIDGET_CONFIG = JSON.parse(JSON.stringify(DEFAULT_CONFIG));

function loadBrandingConfig() {
    try {
        const stored = localStorage.getItem('brandingConfig');
        if (stored) {
            const parsed = JSON.parse(stored);
            WIDGET_CONFIG = deepMerge(DEFAULT_CONFIG, parsed);
        }
    } catch (e) {
        WIDGET_CONFIG = JSON.parse(JSON.stringify(DEFAULT_CONFIG));
    }
}

function deepMerge(defaults, overrides) {
    const result = JSON.parse(JSON.stringify(defaults));
    for (const key in overrides) {
        if (overrides.hasOwnProperty(key)) {
            if (typeof overrides[key] === 'object' && overrides[key] !== null && !Array.isArray(overrides[key])) {
                result[key] = deepMerge(result[key] || {}, overrides[key]);
            } else {
                result[key] = overrides[key];
            }
        }
    }
    return result;
}

function loadGoogleFont(fontName) {
    if (WIDGET_CONFIG.googleFont && fontName) {
        const encodedFont = fontName.replace(/ /g, '+');
        const linkId = 'google-font-dynamic';
        let link = document.getElementById(linkId);
        if (!link) {
            link = document.createElement('link');
            link.id = linkId;
            link.rel = 'stylesheet';
            document.head.appendChild(link);
        }
        link.href = 'https://fonts.googleapis.com/css2?family=' + encodedFont + ':wght@400;700&display=swap';
    }
}

function hexToRgba(hex, opacity) {
    hex = hex.replace('#', '');
    if (hex.length === 3) {
        hex = hex.split('').map(c => c + c).join('');
    }
    const r = parseInt(hex.substring(0, 2), 16);
    const g = parseInt(hex.substring(2, 4), 16);
    const b = parseInt(hex.substring(4, 6), 16);
    return 'rgba(' + r + ', ' + g + ', ' + b + ', ' + (opacity / 100) + ')';
}

function applyWidgetStyles() {
    loadBrandingConfig();
    loadGoogleFont(WIDGET_CONFIG.fontFamily);
    
    const root = document.documentElement;
    
    root.style.setProperty('--font-family', WIDGET_CONFIG.fontFamily);
    root.style.setProperty('--font-weight', WIDGET_CONFIG.fontWeight);
    root.style.setProperty('--text-shadow', WIDGET_CONFIG.textShadow);
    root.style.setProperty('--gap', WIDGET_CONFIG.layout.gap + 'px');
    
    const widgets = ['followers', 'monthly', 'lifetime'];
    
    widgets.forEach(widget => {
        const config = WIDGET_CONFIG.widgets[widget];
        if (!config) return;
        
        const prefix = '--widget-' + widget;
        
        root.style.setProperty(prefix + '-font-size', config.fontSize + 'px');
        root.style.setProperty(prefix + '-label-font-size', config.labelFontSize + 'px');
        root.style.setProperty(prefix + '-text-color', config.colors.text);
        root.style.setProperty(prefix + '-label-color', config.colors.label);
        root.style.setProperty(prefix + '-border-color', config.colors.border);
        
        if (config.background.enabled) {
            const bgColor = config.background.color || '#000000';
            // Allow 0 as a valid opacity value, only use default if undefined/null
            const opacity = config.background.opacity === undefined || config.background.opacity === null ? 30 : config.background.opacity;
            let hex = bgColor;
            if (bgColor.startsWith('rgba')) {
                const match = bgColor.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
                if (match) {
                    const r = parseInt(match[1]).toString(16).padStart(2, '0');
                    const g = parseInt(match[2]).toString(16).padStart(2, '0');
                    const b = parseInt(match[3]).toString(16).padStart(2, '0');
                    hex = '#' + r + g + b;
                }
            }
            const rgba = hexToRgba(hex, opacity);
            root.style.setProperty(prefix + '-bg-color', rgba);
        } else {
            root.style.setProperty(prefix + '-bg-color', 'transparent');
        }
        
        root.style.setProperty(prefix + '-border-width', config.border.width + 'px');
        root.style.setProperty(prefix + '-border-style', config.border.style);
        root.style.setProperty(prefix + '-border-radius', config.border.radius + 'px');
        root.style.setProperty(prefix + '-padding', config.padding.vertical + 'px ' + config.padding.horizontal + 'px');
    });
}

document.addEventListener('DOMContentLoaded', applyWidgetStyles);
